/*******************************************************************************
' MESWEBTuner.vb
'
' Copyright (c) 2007 by Miracom,Inc.
' All rights reserved.
'
' Generated by DevTool XMLGen 1.0
'
' Created at 2025-03-14 16:45:00
'
' Author : Miracom. R&D.
' Description : DevTool Xml Generator Version 1.0
'******************************************************************************/

package com.MESWebServer.h101.Core;


import com.miracom.oneoone.transceiverx.Message;
import com.miracom.oneoone.transceiverx.Session;
import com.miracom.oneoone.transceiverx.StreamTransformer;
import com.miracom.oneoone.transceiverx.parser.DeliveryType;
import com.miracom.oneoone.transceiverx.parser.StreamTransformerImpl;
import com.MESWebServer.h101.Core.MESWEBType.*;


public abstract class MESWEBTuner implements h101dispatcher
{
    private h101stub h101stub;
    // h101dispatcher member
    public Throwable dispatch(Session issuer, Message msg, h101stub h101stub)
    {
        try 
        {
            this.h101stub = h101stub;
            String operation = (String)msg.getProperty(h101stub.XGEN_TAG_OPERATION);
                if (operation.equals("MESWEB_View_MGCMTBLDAT"))
                    recv_MESWEB_View_MGCMTBLDAT(issuer, msg);
                else if (operation.equals("MESWEB_Update_Ftp_Job_File"))
                    recv_MESWEB_Update_Ftp_Job_File(issuer, msg);

            else
            {
                if (DeliveryType.REQUEST == msg.getDeliveryMode())
                    h101stub.sendReply(issuer, msg, msg.createReply(), h101stub.XGEN_ERROR_UNEXPECTED_OPERATION, "Unexpected Operation!");
                return new Exception("Unexpected Operation!(Operation:" + operation + ")");
            }

            return null;
        }
        catch(Exception e)
        {
            return e;
        }
    }

    
    public abstract void MESWEB_View_MGCMTBLDAT(MESWEB_MGCMTBLDAT_In_Tag MESWEB_MGCMTBLDAT_In, MESWEB_MGCMTBLDAT_Out_Tag MESWEB_MGCMTBLDAT_Out) throws Exception;
    private void recv_MESWEB_View_MGCMTBLDAT(Session issuer, Message msg) throws Exception
    {
        StreamTransformer former = new StreamTransformerImpl((byte[])msg.getData());
        MESWEB_MGCMTBLDAT_In_Tag MESWEB_MGCMTBLDAT_In = new MESWEB_MGCMTBLDAT_In_Tag();
        MESWEB_MGCMTBLDAT_Out_Tag MESWEB_MGCMTBLDAT_Out = new MESWEB_MGCMTBLDAT_Out_Tag();

        MESWEBType.transform_MESWEB_MGCMTBLDAT_In_Tag(former, MESWEB_MGCMTBLDAT_In);
        MESWEB_View_MGCMTBLDAT(MESWEB_MGCMTBLDAT_In, MESWEB_MGCMTBLDAT_Out); /* Call User Procedure */
        
        if (DeliveryType.isRequest(msg.getDeliveryMode())) /* Just RequestReply */
        {
            Message rep = msg.createReply();
            former = new StreamTransformerImpl();
            MESWEBType.serialize_MESWEB_MGCMTBLDAT_Out_Tag(former, MESWEB_MGCMTBLDAT_Out);
            rep.putData(former.getBytes());
            h101stub.sendReply(issuer, msg, rep, 0, "");
        }
    }

    public abstract void MESWEB_Update_Ftp_Job_File(MESWEB_Ftp_Job_File_In_Tag MESWEB_Ftp_Job_File_In, MESWEB_Cmn_Out_Tag MESWEB_Cmn_Out) throws Exception;
    private void recv_MESWEB_Update_Ftp_Job_File(Session issuer, Message msg) throws Exception
    {
        StreamTransformer former = new StreamTransformerImpl((byte[])msg.getData());
        MESWEB_Ftp_Job_File_In_Tag MESWEB_Ftp_Job_File_In = new MESWEB_Ftp_Job_File_In_Tag();
        MESWEB_Cmn_Out_Tag MESWEB_Cmn_Out = new MESWEB_Cmn_Out_Tag();

        MESWEBType.transform_MESWEB_Ftp_Job_File_In_Tag(former, MESWEB_Ftp_Job_File_In);
        MESWEB_Update_Ftp_Job_File(MESWEB_Ftp_Job_File_In, MESWEB_Cmn_Out); /* Call User Procedure */
        
        if (DeliveryType.isRequest(msg.getDeliveryMode())) /* Just RequestReply */
        {
            Message rep = msg.createReply();
            former = new StreamTransformerImpl();
            MESWEBType.serialize_MESWEB_Cmn_Out_Tag(former, MESWEB_Cmn_Out);
            rep.putData(former.getBytes());
            h101stub.sendReply(issuer, msg, rep, 0, "");
        }
    }

}

